apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: jupyterhub

bases:
  - ../../base
resources:
  - trusted-cabundle-configmap.yaml
  - jupyterhub-singleuser-profiles-configmap.yaml
