apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/opendatahub-io/s2i-lab-elyra"
    opendatahub.io/notebook-image-name: "Elyra Notebook Image"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with Elyra-AI installed"
  name: s2i-lab-elyra
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.8.12"}]'
      opendatahub.io/notebook-python-dependencies: '[{"name":"elyra","version":"3.12.0"}]'
      openshift.io/imported-from: quay.io/thoth-station/s2i-lab-elyra
    from:
      kind: DockerImage
      name: quay.io/thoth-station/s2i-lab-elyra@sha256:a6f178bf1a5aae123ccc215dbe0f498f4dcd0210cced35483ca65846b1d126ec
    name: "v0.2.1"
    referencePolicy:
      type: Local
